readthedocs

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -21,18 +21,18 @@ build:
       - cd smartdashboard; python -m pip install .
     pre_build:
         - python -m sphinx -b linkcheck doc/ $READTHEDOCS_OUTPUT/linkcheck
-    # post_checkout:
-    #   # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
-    #   # You can add any other files or directories that you'd like here as well,
-    #   # like your docs requirements file, or other files that will change your docs build.
-    #   #
-    #   # If there are no changes (git diff exits with 0) we force the command to return with 183.
-    #   # This is a special exit code on Read the Docs that will cancel the build immediately.
-    #   - |
-    #     if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- doc/ .readthedocs.yaml;
-    #     then
-    #       exit 183;
-    #     fi
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      # You can add any other files or directories that you'd like here as well,
+      # like your docs requirements file, or other files that will change your docs build.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- doc/ .readthedocs.yaml;
+        then
+          exit 183;
+        fi
     # post_checkout:
     #   - git clone https://github.com/CrayLabs/SmartRedis.git
     #   - ln -s ../SmartRedis smartredis
